<?php $posts = $this->getPosts();

        foreach($posts as $post) { ?>
        <h4><?php echo 'Post '. $post->getTitle()?></h4>
            <div class="desc"><?php echo $post->getContent()?></div>
            <hr>
       <?php }
?>
<div class="clearfix"></div>
<h1>Add new post</h1>
<form action="<?php echo Mage::getUrl('magecom/index/saveForm') ?>" method="post" id="my-custom-form">
   <div>
       <h3>Add title</h3>
       <input type="text" class="input-text required-entry" name="title"/>
       </div>
    <div>
        <h3>Add content</h3>
    <textarea name="content" class="input-text required-entry" id="" cols="30" rows="10"></textarea>
        </div>
    <input type="submit"
           style ="width: 200px;
            display: block;
            margin-top: 20px;
            height: 40px;"
           class="my-custom-button" value="Add"/>
</form>

<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('my-custom-form');
    //]]>
</script>
